apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend1
spec:
  selector:
    app: backend
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 5000