name: Backend Docker Image CI for feature/ branches

on:
  push:
    branches: 
      - 'feature/**'
    paths: 
      - 'backend_app/**'
  pull_request:
    branches:
      - 'feature/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - name: Ruff linter
      uses: astral-sh/ruff-action@v4.0.0
      with:
         src: "./backend_app"

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Short SHA
      run:  echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./backend_app/
        file: ./backend_app/Dockerfile
        push: true
        tags: bysdudent/flask-backend:${{ env.SHORT_SHA }}
        
